import { Center, Environment, OrbitControls, useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import React from "react";

export const Macbook3D = ({ position = [-1.85, 0.75, 2], fov = 22 }) => (
    <Canvas
        shadows
        gl={{ preserveDrawingBuffer: true }}
        camera={{ position, fov }}
        eventSource={document.getElementById('root')}
        eventPrefix="client">
        <ambientLight intensity={1} />
        <Environment files="https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/potsdamer_platz_1k.hdr" />
        <Center>
            <Macbook3DModel />
        </Center>
        <OrbitControls enableZoom={false} />
    </Canvas>
)


function Macbook3DModel(props) {
    const { nodes, materials } = useGLTF(
        "/assets/3d/macBook.glb"
    );
    return (
        <group {...props} dispose={null}>
            <group scale={0.0175}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.xVreGKoBGSZYMij.geometry}
                    material={materials.dKLyhhkbEyMrqky}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CTBERffHyoCSDBm_0.geometry}
                    material={materials.YjmXmicdBWsFQyD}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.hczGzWOWpedUDYd_0.geometry}
                    material={materials.pEUnNAGXCoAFoUk}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.biHEvGDNnTqamRb.geometry}
                    material={materials.dFfswgailNMtaYj}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.TyOrApjEOLhYCaF.geometry}
                    material={materials.AZirwHJdxxcChtp}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.vrIckaCELZpnnNK.geometry}
                    material={materials.dkOmcmuFedorUKC}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SadnAkehSlxIwKv.geometry}
                    material={materials.VNZklasZKSWjWUk}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.OrhpMXCxeprcNok.geometry}
                    material={materials.OfvrpEsWzbOpbcs}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.aLWGnOLpsFWVSfy.geometry}
                    material={materials.iFCKstMLETFqCmZ}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WDUVUVPpNjdIPkb.geometry}
                    material={materials.ZPlxrBOYjSNYvVB}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NqUinIWcwSlXpvt.geometry}
                    material={materials.rvYnnyqXrbFJXxh}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MaufYfIBnxcfRgH.geometry}
                    material={materials.SsSIPrCyVNTOxvd}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.aIqeGXayDxWnOWQ.geometry}
                    material={materials.EKOOVJzobzfBYEj}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.HrtjMXqDCcINmDE_0.geometry}
                    material={materials.BfIgIOaUEgyoEft}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.zWqVyCKpTAuZNiu_0.geometry}
                    material={materials.zFJMMvikHFjtmzd}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MYVKQTLmUkzzlBj_0.geometry}
                    material={materials.jIhmcgKbjDOICsY}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.qEJjkxdFZFWJWzR_0.geometry}
                    material={materials.JKvAHnqjqlqshmY}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.lvlCIzdfTmsrnsM.geometry}
                    material={materials.iFCKstMLETFqCmZ}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.eeWSraIVipLsSmX_0.geometry}
                    material={materials.JKvAHnqjqlqshmY}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.PgbYkhvRdcmMeGL.geometry}
                    material={materials.wOIDWopwzKBeTNU}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rktWdhtZkCSmqne.geometry}
                    material={materials.ZrrjpMZNDbttBCc}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.hztTkkTJBJTZDmk.geometry}
                    material={materials.ZrrjpMZNDbttBCc}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.bHBjPHbrqJmhyoR.geometry}
                    material={materials.ZrrjpMZNDbttBCc}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.HHcJitDCPTdgnFk.geometry}
                    material={materials.RMDHOHZakhhXXHT}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.DRGkWmkJlgmNDJU.geometry}
                    material={materials.RMDHOHZakhhXXHT}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.KMwpdMtieDqmHVU.geometry}
                    material={materials.RMDHOHZakhhXXHT}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.KgPDMIRPrxAynTV.geometry}
                    material={materials.hZBlDyddxAQhuPm}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.XwGJfoaIrduFPcU.geometry}
                    material={materials.YjmXmicdBWsFQyD}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ACMWKGtOCqXifQY.geometry}
                    material={materials.RMDHOHZakhhXXHT}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.BkHyotPbPWzwAAj.geometry}
                    material={materials.sRPrqogRtliLLae}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.bkcxDtALZjuqGGQ.geometry}
                    material={materials.RMDHOHZakhhXXHT}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ebZHPVwKTmqvgbU.geometry}
                    material={materials.kDpbvvjwMgCSCmF}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.uSnVzUkbvcGaVtm.geometry}
                    material={materials.AqVxlXuHIFahLKs}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.znOBoeqnOAcWvld.geometry}
                    material={materials.dKLyhhkbEyMrqky}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.tIZmzvOOHrlOFci.geometry}
                    material={materials.oKQWdLrXUCbYByI}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.UmfOhraHkqkMHJr.geometry}
                    material={materials.OFvWomWIIUgmKKA}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.roXkINNmErodbSy.geometry}
                    material={materials.oKQWdLrXUCbYByI}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wWWhLQmmNVhThGV.geometry}
                    material={materials.OFvWomWIIUgmKKA}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.JoRHkRchuIHZFdI.geometry}
                    material={materials.mEMAJQfiigHeUXV}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.qJLFXXZhlqhKvcM.geometry}
                    material={materials.mEMAJQfiigHeUXV}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.thJvyyEdPZIkQGr.geometry}
                    material={materials.OFvWomWIIUgmKKA}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.juMIjHdkYweLlGP.geometry}
                    material={materials.NzmRSNqyvNKhkmK}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.zNYAavJLMZZchIX.geometry}
                    material={materials.ASadxrcBIAXFnLn}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.bzbXKgxvWZbXAqu.geometry}
                    material={materials.JKvAHnqjqlqshmY}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.guzkNjLPdYYIFbm.geometry}
                    material={materials.oINmXIPcNKkHSJV}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.CkZgGMshUOhytMM.geometry}
                    material={materials.AvocVUvikCzzMtu}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.oiLbjgjnUUhPosp.geometry}
                    material={materials.AvocVUvikCzzMtu}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.nDWhlgWONddUcnN.geometry}
                    material={materials.tyKqaDjBmuwfmrZ}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.VAcTKRVsYcEMWxB.geometry}
                    material={materials.dkOmcmuFedorUKC}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/assets/3d/macBook.glb");